### ISSUE TITLE
Endpoint does not exist error when starting DevGateway

### ISSUE THREAD

**Issue by q-rebeccawalters** [microsoft/Microsoft-Fabric-workload-development-sample#101]
I am seeing the following error when running DevGateway.
```
[2024-09-24 16:06:05.335] [Error] Relay listener went offline, terminating, ex: Microsoft.Azure.Relay.EndpointNotFoundException: Endpoint does not exist. TrackingId:ec2e6d86-90c7-40c0-b6cc-7ad91ccd8c6c_G57, 
SystemTracker:sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/f1e94993-9788-4337-9441-dadee1b415a6_org.quantexa_workload, Timestamp:2024-09-24T15:06:04
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '404' when status code '101' was expected.
   at Microsoft.Azure.Relay.WebSockets.NetCore21.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.Azure.Relay.WebSockets.NetCore21.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.CloseOrAbortWebSocketAsync(Task`1 connectTask, Boolean abort, WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
```

I see the issue was raised [here](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/issues/76) as a transient problem but I have been experiencing the issue for over an hour. Is someone able to help me with this? Thank you

**Comment by ramizsha** [comment]
@q-rebeccawalters Is there someone else developing on the same capacity?
Also, how often do you see this? and after how much time from starting the devgateway does this appear?

**Comment by q-rebeccawalters** [comment]
@ramizsha thanks for your response - no it is just me on my capacity. 

It is very intermittent. For example it worked fine for an hour this morning, then I had the error again for 2 hours, then fine again for 2 hours, now the error is back. 

I get the error exactly 1 minute after starting the dev gateway. I believe another member of our team, @q-brynmonroe, is also having the same issue.

**Comment by q-rebeccawalters** [comment]
@ramizsha hi it's happening again today, I get a different tracking number so thought I'd post that here 
```
[2024-09-26 14:56:18.687] [Error] Relay listener went offline, terminating, ex: Microsoft.Azure.Relay.EndpointNotFoundException: Endpoint does not exist. TrackingId:2ebf4b78-3937-4258-863c-9e95199329fd_G1, SystemTracker:sb://pbip-west
europe-wl-proxy-relay-5.servicebus.windows.net/46748c56-ba28-4bb5-85fd-db75123e047b_org.quantexa_workload, Timestamp:2024-09-26T13:56:18
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '404' when status code '101' was expected.
   at Microsoft.Azure.Relay.WebSockets.NetCore21.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.Azure.Relay.WebSockets.NetCore21.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.CloseOrAbortWebSocketAsync(Task`1 connectTask, Boolean abort, WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken) 
```

**Comment by TomPridham** [comment]
we have also intermittently seen this error

**Comment by q-nicolechoi** [comment]
I've also started to see this error
```
[2024-10-30 11:05:00.202] [Error] Relay listener went offline, terminating, ex: Microsoft.Azure.Relay.EndpointNotFoundException: Endpoint does not exist. TrackingId:b8dfee44-138a-44fc-90a4-4057cc2225dc_G10, SystemTracker:sb://pbip-westeurope-wl-proxy-relay-3.servicebus.windows.net/9f07ff5e-2067-4cc9-9fed-1ebfc34447b9_org.quantexa_workload, Timestamp:2024-10-30T11:04:57
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '404' when status code '101' was expected.
   at Microsoft.Azure.Relay.WebSockets.NetCore21.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.Azure.Relay.WebSockets.NetCore21.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.ConnectAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Relay.HybridConnectionListener.ControlConnection.CloseOrAbortWebSocketAsync(Task`1 connectTask, Boolean abort, WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
```

**Comment by anitamayorov** [comment]
Hi @q-rebeccawalters, @q-nicolechoi, @TomPridham 
The issue you are experiencing is a known issue and under investigation. For now, as a workaround please terminate the DevGateway process and relaunch it after ~1 minute. We apologize for any inconvenience.

**Comment by anitamayorov** [comment]
Hi, currently the issue is still investigated. For now, please as explained previously terminate the DevGateway process and relaunch it after ~1 minute. Please make sure to terminate all DevGateway processes if exist prior to relaunching a new one to make sure you are working with only one instance of DevGateway.
