### ISSUE TITLE
Help debugging new app registration

### ISSUE THREAD

**Issue by box-turtle** [microsoft/Microsoft-Fabric-workload-development-sample#11]
Is there any documentation for using the script  `Authentication/CreateDevAADApp.ps1`?

Is that what we are supposed to be using for creating an app registration? The settings in that script are not the same as the various instructions for doing this, is the process really finalized?

Can anyone provide advice for debugging a new app registration? I tried using it for the Sample app where I renamed all references to the workload and workload item to the new names. The BE app compiles fine, but when I try to run devgateway.exe it fails to register the app with fabric, giving the following message:

```
[2024-06-05 16:29:23.932] [Verbose] Reading workload manifest package from path: \Users\Administrator\source\repos\Microsoft-Fabric-workload-development-sample\Backend\src\bin\Debug\ManifestPackage.1.0.0.nupkg
[2024-06-05 16:29:23.935] [Verbose] Retrieved workload manifest package from path: \Users\Administrator\source\repos\Microsoft-Fabric-workload-development-sample\Backend\src\bin\Debug\ManifestPackage.1.0.0.nupkg
[2024-06-05 16:29:24.017] [Verbose] Sending request to the Fabric registration endpoint v1/capacities/02287398-3577-41cf-bdbc-2a1cc58cc2dd/workloads/registerDevInstance.
Unhandled exception. Microsoft.Fabric.Workload.Core.Internal.Services.Exceptions.DevInstanceRegistrationFailedException: Dev instance registration call Method: POST, RequestUri: 'https://api.fabric.microsoft.com/v1/capacities/02287398-3577-41cf-bdbc-2a1cc58cc2dd/workloads/registerDevInstance', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCIsImtpZCI6IkwxS2ZLRklfam5YYndXYzIyeFp4dzFzVUhIMCJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMzkxYzhjNGMtNmEyYS00MGZkLWFiOTgtMjI2YjZiYWE1MTU1LyIsImlhdCI6MTcxNzYxOTA2NCwibmJmIjoxNzE3NjE5MDY0LCJleHAiOjE3MTc2MjMxNjEsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVFFBeS84V0FBQUFyZmlwd3RHblIzRW12WVo1eEN0SXBlTUpzci9PVHljNWRqMjZVeThDaTRCOU1Pamw3aXpDenhkTzNsMGRlWE16IiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6ImM1YTM2MGZmLTc0MTgtNDBlNy04NTYzLTcyYmQ2ZTM3ZjY2MyIsImFwcGlkYWNyIjoiMCIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjE0MS4yMDYuMjQ2LjEwIiwibmFtZSI6IlBhbm5lZXJzZWx2YW0sIFZpbWFscmFqIiwib2lkIjoiMGQ1N2ExOTUtMWFkZS00NzNkLWJhM2YtZDAyYjllMWQ3NDVlIiwicHVpZCI6IjEwMDMyMDAyRkQ5RUYzNzciLCJyaCI6IjAuQVZrQVRJd2NPU3BxX1VDcm1DSnJhNnBSVlFrQUFBQUFBQUFBd0FBQUFBQUFBQUQ3QVAwLiIsInNjcCI6IkRldlguUmVhZFdyaXRlLkFsbCIsInN1YiI6InBiRTRiRGtlbzNRVjNWYzZRanRZeXBvZ1ZlQV8zWmxuZEMxUU90TzFBNDQiLCJ0aWQiOiIzOTFjOGM0Yy02YTJhLTQwZmQtYWI5OC0yMjZiNmJhYTUxNTUiLCJ1bmlxdWVfbmFtZSI6InZpbWFscmFqLnBhbm5lZXJzZWx2YW1AdGVyYWNsb3VkZGV2Lm9ubWljcm9zb2Z0LmNvbSIsInVwbiI6InZpbWFscmFqLnBhbm5lZXJzZWx2YW1AdGVyYWNsb3VkZGV2Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6Ilp2a1lodkFVazBtMmZUQW9UNkU4QUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImE5ZWE4OTk2LTEyMmYtNGM3NC05NTIwLThlZGNkMTkyODI2YyIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdfQ.mjyzg2LTOBQJod8u8tXnNSx7m3IpZDWo0sVR3sZy40mEAFSXHzgj8Ou6CQImNZnfPorveWnA1GsDhP3Mv5sOiu-aSpyeH9lgIJMRzSd0sTRU4FyRuOOr9Lw8yiOpL18Ajo9QK3UL-g5Z2_WIZIubwH-k2Zjy7tM6D1DlwEkX95yqFx-P3l8uYmYzMQlqnYGUOQCI_7oYffqYV8t62KaNW1XwTsU7pHj3uezqcECfFbrf0M2ukLXHvK0oKnubZLPWMdyuFpKNZ4GdOdgSfiIxoZ3NsL86SCToa3iOKk5ufYKc0xzRXYuOYnwBsaYJJkN6q_yU4qY-IhHCHs9TPH6rlQ
  Accept: application/json
  User-Agent: Microsoft.Fabric.Workload.Core.Internal/2024.6.2.17
  Content-Type: application/json; charset=utf-8
  Content-Length: 5780
} was not successful, HTTP status code: BadRequest, reason: Bad Request, response: {"requestId":"287f48d0-2dbf-4a12-9c08-3c5596ffc484","errorCode":"UnknownError","message":"An unexpected error occurred while processing the request"}
   at Microsoft.Fabric.Workload.Core.Internal.Services.PbiSharedClient.RegisterCurrentDevInstanceAsync(WorkloadRegistrationRequest requestBody, Guid capacityGuid, String accessToken)
   at Microsoft.Fabric.Workload.Core.Internal.DevConnection.RegisterDevInstanceAsync(DevModeParameters devModeParameter, String userToken)
   at Microsoft.Fabric.Workload.Core.Internal.DevConnection.InitializeAsync(DevModeParameters devModeParameters, IList`1 endpointMappings)
   at Microsoft.Fabric.Workload.DevGateway.DevGatewayApplication.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Fabric.Workload.DevGateway.Program.Main(String[] args)
   at Microsoft.Fabric.Workload.DevGateway.Program.<Main>(String[] args)
```

Are there any limitations around the names? I was using "Teradata.AIUnlimited.Notebook" for the workload/item name.

Any way to enable more logging on this, or see a more helpful error message?

thanks

**Comment by box-turtle** [comment]
Here is the manifest for the registration:

```json
{
	"id": "a89396be-ec81-4278-a1ec-a4ae2970bb95",
	"acceptMappedClaims": null,
	"accessTokenAcceptedVersion": null,
	"addIns": [],
	"allowPublicClient": null,
	"appId": "8c477649-821f-4d62-90eb-f19b7feda64a",
	"appRoles": [],
	"oauth2AllowUrlPathMatching": false,
	"createdDateTime": "2024-06-04T13:00:48Z",
	"description": null,
	"certification": null,
	"disabledByMicrosoftStatus": null,
	"groupMembershipClaims": "None",
	"identifierUris": [
		"api://localdevinstance/391c8c4c-6a2a-40fd-ab98-226b6baa5155/Teradata.AIUnlimited"
	],
	"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "Teradata AI Unlimited Dev",
	"notes": null,
	"oauth2AllowIdTokenImplicitFlow": false,
	"oauth2AllowImplicitFlow": false,
	"oauth2Permissions": [
		{
			"adminConsentDescription": "read fabric items",
			"adminConsentDisplayName": "Read Fabric items",
			"id": "fcc58774-91bf-45ee-bcbc-33154a0a31a8",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "Admin",
			"userConsentDescription": "read fabric items",
			"userConsentDisplayName": "Read Fabric items",
			"value": "Item1.Read.All"
		},
		{
			"adminConsentDescription": "Read write workload items",
			"adminConsentDisplayName": "Read write workload items",
			"id": "ff0d7f65-df5c-4a2c-be58-a51cc690175b",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "Admin",
			"userConsentDescription": "Read write workload items",
			"userConsentDisplayName": "Read write workload items",
			"value": "Item1.ReadWrite.All"
		},
		{
			"adminConsentDescription": "FabricLakehouse.Read.All",
			"adminConsentDisplayName": "FabricLakehouse.Read.All",
			"id": "ac157f02-bf77-4b50-9d3d-00e7bedb9e0f",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "Admin",
			"userConsentDescription": "FabricLakehouse.Read.All",
			"userConsentDisplayName": "FabricLakehouse.Read.All",
			"value": "FabricLakehouse.Read.All"
		},
		{
			"adminConsentDescription": "FabricLakehouse.ReadWrite.All",
			"adminConsentDisplayName": "FabricLakehouse.ReadWrite.All",
			"id": "5b22811c-0325-4498-bedb-48b11102bc3b",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "Admin",
			"userConsentDescription": "FabricLakehouse.ReadWrite.All",
			"userConsentDisplayName": "FabricLakehouse.ReadWrite.All",
			"value": "FabricLakehouse.ReadWrite.All"
		},
		{
			"adminConsentDescription": "Allow workload to interact with Fabric",
			"adminConsentDisplayName": "FabricWorkloadControl",
			"id": "bcf8c438-a058-42a3-af26-a89efb57bd29",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "Admin",
			"userConsentDescription": "Allow workload to interact with Fabric",
			"userConsentDisplayName": "FabricWorkloadControl",
			"value": "FabricWorkloadControl"
		},
		{
			"adminConsentDescription": "Lakehouse.ReadWrite.All",
			"adminConsentDisplayName": "Lakehouse.ReadWrite.All",
			"id": "b052d97d-e492-4527-979d-6b4388f86fb5",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "Admin",
			"userConsentDescription": null,
			"userConsentDisplayName": null,
			"value": "Lakehouse.ReadWrite.All"
		}
	],
	"oauth2RequirePostResponse": false,
	"optionalClaims": {
		"idToken": [],
		"accessToken": [
			{
				"name": "idtyp",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": []
	},
	"orgRestrictions": [],
	"parentalControlSettings": {
		"countriesBlockedForMinors": [],
		"legalAgeGroupRule": "Allow"
	},
	"passwordCredentials": [
		{
			"customKeyIdentifier": null,
			"endDate": "2024-12-01T14:14:54.431Z",
			"keyId": "63239054-1d11-4ff5-a79b-ee4babbb753b",
			"startDate": "2024-06-04T13:14:54.431Z",
			"value": null,
			"createdOn": "2024-06-04T13:15:16.6901458Z",
			"hint": "zU4",
			"displayName": "ai unlmited dev"
		}
	],
	"preAuthorizedApplications": [
		{
			"appId": "871c010f-5e61-4fb1-83ac-98610a7e9110",
			"permissionIds": [
				"fcc58774-91bf-45ee-bcbc-33154a0a31a8",
				"ff0d7f65-df5c-4a2c-be58-a51cc690175b",
				"ac157f02-bf77-4b50-9d3d-00e7bedb9e0f",
				"5b22811c-0325-4498-bedb-48b11102bc3b",
				"b052d97d-e492-4527-979d-6b4388f86fb5"
			]
		},
		{
			"appId": "00000009-0000-0000-c000-000000000000",
			"permissionIds": [
				"bcf8c438-a058-42a3-af26-a89efb57bd29"
			]
		}
	],
	"publisherDomain": "teraclouddev.onmicrosoft.com",
	"replyUrlsWithType": [
		{
			"url": "http://localhost:60006/close",
			"type": "Spa"
		}
	],
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000009-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "b2f1b2fa-f35c-407c-979c-a858a808ba85",
					"type": "Scope"
				},
				{
					"id": "7a27a256-301d-4359-b77b-c2b759d2e362",
					"type": "Scope"
				},
				{
					"id": "d2bc95fc-440e-4b0e-bafd-97182de7aef5",
					"type": "Scope"
				},
				{
					"id": "caf40b1a-f10e-4da1-86e4-5fda17eb2b07",
					"type": "Scope"
				},
				{
					"id": "02e8d710-956c-4760-b996-2e83935c2cf5",
					"type": "Scope"
				},
				{
					"id": "eee83281-2212-467d-b9e3-2aadfb170f33",
					"type": "Scope"
				},
				{
					"id": "13060bfd-9305-4ec6-8388-8916580f4fa9",
					"type": "Scope"
				}
			]
		},
		{
			"resourceAppId": "e406a681-f3d4-42a8-90b6-c2b029497af1",
			"resourceAccess": [
				{
					"id": "03e0da56-190b-40ad-a80c-ea378c433f7f",
					"type": "Scope"
				}
			]
		},
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetadataUrl": null,
	"signInUrl": null,
	"signInAudience": "AzureADMultipleOrgs",
	"tags": [],
	"tokenEncryptionKeyId": null
}
```

**Comment by box-turtle** [comment]
OK so the only change I had to make to my app to make it so that Devgateway can successfully register it was to change the application id URI from

api://localdevinstance/391c8c4c-6a2a-40fd-ab98-226b6baa5155/Teradata.AIUnlimited

to

api://localdevinstance/391c8c4c-6a2a-40fd-ab98-226b6baa5155/Org.Teradata

Might be a good idea to mention that this pattern is required, and maybe even some explanation as to why it is required? It doesn't seem to be enforced in the powershell script.

Seems like the configuration of fabric has a lot of "magic strings" involved. Like why is the item read/readwrite permission called `Item1.Read.All`? Does that work for all item types I create?

**Comment by ramizsha** [comment]
@box-turtle It is mentioned [here](https://github.com/microsoft/Microsoft-Fabric-developer-sample/blob/main/Backend/src/Packages/manifest/README.md#workloadname-attribute) that your workload name needs to start with Org - however we will add a small note to the instructions of the usage of the script.

Regarding Item1.Read.All, this is only a sample scope that is used for data plane APIs (calls from your frontend directly to your backend), you can change this to any scope name you like - if you do, make sure to change it on your application in Entra Id and in your BE.
Please note that the only scope that you are required to have on your application is "FabricWorkloadControl" that is used in calls from Fabric to your backend, other scopes are customizable - You can find examples of using such scopes [here](https://github.com/microsoft/Microsoft-Fabric-developer-sample/blob/main/Backend/src/Controllers/FabricExtensionController.cs) (see AuthenticateDataPlaneCall)

**Comment by ramizsha** [comment]
Regarding the Org. pattern we are working on adding the required documentation, we will also update the script to have an enforcement on this.
Regarding Item1.Read.All, this is only a sample scope that is used for data plane APIs (calls from your frontend directly to your backend), you can change this to any scope name you like - if you do, make sure to change it on your application in Entra Id and in your BE.
Please note that the only scope that you are required to have on your application is "FabricWorkloadControl" that is used in calls from Fabric to your backend, other scopes are customizable - You can find examples of using such scopes [here](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/blob/main/Backend/src/Controllers/FabricExtensionController.cs) (see AuthenticateDataPlaneCall)
