### ISSUE TITLE
DevGateway timeout when trying to access project

### ISSUE THREAD

**Issue by q-rebeccawalters** [microsoft/Microsoft-Fabric-workload-development-sample#171]
when starting DevGateway and trying to access a project I get the following error: 
```
[2024-12-10 10:36:09.737] [Error] Relay Listener got error from forwarding call sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/46748c56-ba28-4bb5-85fd-db75123e047b_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/c91388af-9c37-437
2-9aae-5aeae996ed3c/payload?api-version=2016-10-01
[2024-12-10 10:36:09.738] Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Fabric.Platform.RelayToWeb.Internal.RelayListener.<StartAsync>b__7_0(RelayRequest relayRequest)
```
not sure what is causing the timeout, have tried just restarting the DevGateway and it doesn't solve the issue.

**Comment by shaym83** [comment]
@q-rebeccawalters - can you please explain what you mean by "trying to access project"?
Can you also share the DevGateway's output?

**Comment by q-benwillis** [comment]
@shaym83 

>can you please explain what you mean by "trying to access project"?
Trying to open a workload item created using the local dev workload

> Can you also share the DevGateway's output?
I believe the above is DevGateway's output or are you after something else?

**Comment by q-rebeccawalters** [comment]
@shaym83 yes sure, I mean that when I try to click on a fabric workload project, I eventually get the error I posted above. I'll provide more of the DevGateway output if that's helpful 
```
[2024-12-10 10:53:26.155] [Information] Starting DevGateway...
[2024-12-10 10:53:26.258] [Information] Getting user credentials...
[2024-12-10 10:53:29.545] [Information] Interactive user AAD token received
[2024-12-10 10:53:29.547] [Information] Registering dev instance...
[2024-12-10 10:53:44.953] [Information] Dev instance registered successfully.
[2024-12-10 10:53:44.954] [Information] Starting relay bridge...
[2024-12-10 10:53:45.090] [Information] Started relay bridge service 5189e3a5-4c04-470d-829e-e7f97d05b0ec
[2024-12-10 10:53:45.093] [Information] DevGateway started
[2024-12-10 10:53:55.170] [Information] Start forwarding request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/b4eef21f-0da0-4c1f-87ac-551b5fe2401f/payload?api-version=2016-10-01
[2024-12-10 10:54:58.049] [Information] Start forwarding request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/b4eef21f-0da0-4c1f-87ac-551b5fe2401f/payload?api-version=2016-10-01
[2024-12-10 10:55:35.183] [Error] Relay Listener got error from forwarding call sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/46748c56-ba28-4bb5-85fd-db75123e047b_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/b4eef21f-0da0-4c1
f-87ac-551b5fe2401f/payload?api-version=2016-10-01
[2024-12-10 10:55:35.184] Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Fabric.Platform.RelayToWeb.Internal.RelayListener.<StartAsync>b__7_0(RelayRequest relayRequest)
```

**Comment by shaym83** [comment]
@q-rebeccawalters - this can be a transient issue, or a network issue, or even something on the workload's side (for example, stopping on a breakpoint and not releasing it).

To allow further investigation, can you please:

1. Download the latest DevGateway from [download center](https://www.microsoft.com/en-us/download/details.aspx?id=105993&msockid=04def79bb1cf62870257e32eb0526353)
2. Run it with Verbose trace levels, by adding this to the command line: "-LogLevel Verbose".
3. Once you have this setup, please reproduce the issue and send the DevGateway output.

**Comment by q-rebeccawalters** [comment]
@shaym83 have downloaded the latest DevGateway and this is the output from the verbose trace level 
```
[11/12 11:07:55.408] dbug: Hosting starting
[11/12 11:07:55.465] info: Starting DevGateway...
[11/12 11:07:55.467] trce: Starting in dev mode: Microsoft.Fabric.Workloads.DevGateway.DevGatewayOptions
[11/12 11:07:55.472] trce: Getting user AAD token interactively with audience: https://analysis.windows.net/powerbi/api/.default...
[11/12 11:07:58.701] trce: Got the user's token from client application
[11/12 11:07:58.702] trce: Get token for resource resourceId authority https://login.windows.net/common
[11/12 11:07:58.703] info: Interactive user AAD token received
[11/12 11:07:58.704] info: Registering dev instance...
[11/12 11:07:58.705] trce: Reading workload manifest package from path: C:/Users/RebeccaWalters/Projects/quantexa-platform/projects/fabric-workload/fabric-dev-gateway/build/dist/ManifestPackage.zip
[11/12 11:07:58.727] trce: Retrieved workload manifest package from path: C:/Users/RebeccaWalters/Projects/quantexa-platform/projects/fabric-workload/fabric-dev-gateway/build/dist/ManifestPackage.zip
[11/12 11:07:58.790] trce: Sending request to the Fabric registration endpoint v1/capacities/78d7b92b-ff58-4553-91dd-db1b31f212ab/__private/workloads/registerDevInstance.
[11/12 11:08:50.217] trce: Got response successfully from the Fabric's registration endpoint v1/capacities/78d7b92b-ff58-4553-91dd-db1b31f212ab/__private/workloads/registerDevInstance. Response: {"devInstanceGuid":"b17e1869-f8f8-4a76-82d1-32a981571751","platformApiUri":"https://pbip-westeurope-wl-proxy-relay-3.servicebus.windows.net:443/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_platform/endpoint/Microsoft.Fabric.Platform","platformApiAuthInfo":null,"workloadRelayListenerConfig":{"listenerKeyInfo":{"keyName":"ec10a2f6-121a-4176-9554-22b96acdf7c8","key":"E8n/jI0UXtgUGwbg8CR3w0jSX10FmiAYV+ARmDB+YPE=","connectionString":"Endpoint=sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/;SharedAccessKeyName=ec10a2f6-121a-4176-9554-22b96acdf7c8;SharedAccessKey=E8n/jI0UXtgUGwbg8CR3w0jSX10FmiAYV+ARmDB+YPE=;EntityPath=78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload"}},"startupParameters":{"workloadId":null,"workloadInstanceGuid":null}}
[11/12 11:08:50.241] trce: DevInstanceRegistrationResponse: [ DevInstanceGuid: b17e1869-f8f8-4a76-82d1-32a981571751, PlatformApiUri: https://pbip-westeurope-wl-proxy-relay-3.servicebus.windows.net:443/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_platform/endpoint/Microsoft.Fabric.Platform, StartupParameters: StartupParameters[ WorkloadId: , WorkloadInstanceGuid:  ], RelayNamespace: , Relay ConnectionName: , Relay ServiceBusEndpoint:  ]
[11/12 11:08:50.242] info: Dev instance registered successfully
[11/12 11:08:50.244] trce: Starting relay bridge..
[11/12 11:08:50.250] trce: Configured mappings: [{"IncomingUrlPathPrefix":"/Microsoft.Fabric.Workload/Platform","OutgoingBaseUrl":"http://127.0.0.1:8080/api/fabric/"}]
[11/12 11:08:50.261] trce: Starting Relay listener at: sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload
[11/12 11:08:50.392] trce: Started Relay listener
[11/12 11:08:50.394] trce: Started relay bridge service 7b37dee3-000d-465a-969b-1b7af2de75ca
[11/12 11:08:50.396] trce: Will not start workload to orchestrator health check monitor because it is disabled by the configs
[11/12 11:08:50.397] info: DevGateway started
[11/12 11:08:50.399] dbug: Hosting started
[11/12 11:08:57.143] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:08:57.148] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=e26059ff-7421-a1ea-b02b-b90dce013a94
[11/12 11:09:04.933] trce: Health Check received
[11/12 11:09:17.262] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:09:17.265] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=d7dbc99b-5add-4b2d-6684-37140a7f8399
[11/12 11:09:19.996] trce: Health Check received
[11/12 11:09:35.029] trce: Health Check received
[11/12 11:09:50.059] trce: Health Check received
[11/12 11:09:59.990] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:09:59.993] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=e26059ff-7421-a1ea-b02b-b90dce013a94
[11/12 11:10:05.091] trce: Health Check received
[11/12 11:10:20.124] trce: Health Check received
[11/12 11:10:20.335] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:10:20.337] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=d7dbc99b-5add-4b2d-6684-37140a7f8399
[11/12 11:10:35.161] trce: Health Check received
[11/12 11:10:37.157] fail: Error occurred during forwarding of request sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:10:50.208] trce: Health Check received
[11/12 11:10:57.279] fail: Error occurred during forwarding of request sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:11:03.081] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:11:03.083] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=e26059ff-7421-a1ea-b02b-b90dce013a94
[11/12 11:11:05.239] trce: Health Check received
[11/12 11:11:20.257] trce: Health Check received
[11/12 11:11:23.391] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:11:23.392] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=d7dbc99b-5add-4b2d-6684-37140a7f8399
[11/12 11:11:35.298] trce: Health Check received
[11/12 11:11:39.997] fail: Error occurred during forwarding of request sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:11:50.312] trce: Health Check received
[11/12 11:12:00.350] fail: Error occurred during forwarding of request sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:12:05.345] trce: Health Check received
[11/12 11:12:06.171] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:12:06.172] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=e26059ff-7421-a1ea-b02b-b90dce013a94
[11/12 11:12:20.379] trce: Health Check received
[11/12 11:12:26.408] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:12:26.408] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=d7dbc99b-5add-4b2d-6684-37140a7f8399
[11/12 11:12:35.413] trce: Health Check received
[11/12 11:12:43.101] fail: Error occurred during forwarding of request sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:12:50.445] trce: Health Check received
[11/12 11:13:03.395] fail: Error occurred during forwarding of request sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:13:05.462] trce: Health Check received
[11/12 11:13:09.223] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:13:09.225] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=e26059ff-7421-a1ea-b02b-b90dce013a94
[11/12 11:13:12.969] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:13:12.970] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=68fa7d81-1635-ae8d-584f-85c624e9c389
[11/12 11:13:20.494] trce: Health Check received
[11/12 11:13:29.520] trce: Received GET request for sb://pbip-westeurope-wl-proxy-relay-5.servicebus.windows.net/78d7b92b-ff58-4553-91dd-db1b31f212ab_org.quantexa_workload/Microsoft.Fabric.Workload/Platform/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01
[11/12 11:13:29.522] info: Forwarding GET request to http://127.0.0.1:8080/api/fabric/workspaces/80cd68e9-e15b-4fe2-a9f5-ada036e13354/items/Org.Quantexa.Project/06dcf087-44db-4fcd-b9aa-e5f1c6058c33/payload?api-version=2016-10-01 | Headers: ActivityId=de6f7e70-0060-4de3-a319-9decb0e4fc5b, RequestId=d7dbc99b-5add-4b2d-6684-37140a7f8399
```

**Comment by shaym83** [comment]
You seem to have been affected by a temporary outage of our backend services, in your specific region.
Are you still seeing this issue? it should be mitigated now.

**Comment by q-rebeccawalters** [comment]
hi @shaym83 I am no longer seeing this issue, I am however now getting this issue https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/issues/101

**Comment by q-rebeccawalters** [comment]
hi @shaym83 I'm seeing the timeout error again, is this something that is transient? Dev gateway hasn't been working for me at all for the past 3 days with either the timeout error, or the endpoint does not exist error that I raised [here](https://github.com/microsoft/Microsoft-Fabric-workload-development-sample/issues/101)

**Comment by shaym83** [comment]
@q-rebeccawalters looking at the traces, I think you have an issue with the DevGateway setup.
The artifact you are trying to access (Object ID: 06dcf087-44db-4fcd-b9aa-e5f1c6058c33) resides in a workspace that is under capacity with Object ID: ### 46748c56-ba28-4bb5-85fd-db75123e047b.
However, you are connecting the DevGateway to capacity with Object ID: ### 78d7b92b-ff58-4553-91dd-db1b31f212ab.
With this setup, you can only view artifacts in workspaces under capacity 78d7b92b-ff58-4553-91dd-db1b31f212ab.

**Comment by q-rebeccawalters** [comment]
@shaym83 sorry I'm confused, I get the timeout error I originally posted about even when I am creating a new project. 

It is my understand that if I am creating a new project under capacity with Object ID: ### 46748c56-ba28-4bb5-85fd-db75123e047b then I should be able to access it? I am still getting the timeout error today

**Comment by yonadiv** [comment]
Hey, no, you can only access items (projects) you create under the capacity you are logged into when developing. 
You need to update the workload-dev-mode.Json to contain the capacity object id 46748c56-ba28-4bb5-85fd-db75123e047b instead of the capacity 78d7b92b-ff58-4553-91dd-db1b31f212ab and then rerun the dev gateway. and then you would be able to access items (projects) under any workspace that is running on this capacity.

**Comment by q-rebeccawalters** [comment]
thanks for your help, I'm no longer seeing this issue
